#' Random variation around a Sine curve (n = 33)
#'
#' The \code{x} values are equally spaced points at
#'   0, \eqn{pi / (n - 1)}, ..., \eqn{2 pi}. whereas the \code{y} values were
#'   generated by adding draws from a random normal distribution
#'   (\eqn{s.d. = 0.1}) around a Sine curve.
"EgData33"

#' Random variation around a Sine curve (n = 65)
#'
#' The \code{x} values are equally spaced points at
#'   0, \eqn{pi / (n - 1)}, ..., \eqn{2 pi}. whereas the \code{y} values were
#'   generated by adding draws from a random normal distribution
#'   (\eqn{s.d. = 0.1}) around a Sine curve.
"EgData65"

#' Random variation around a Sine curve (n = 129)
#'
#' The \code{x} values are equally spaced points at
#'   0, \eqn{pi / (n - 1)}, ..., \eqn{2 pi}. whereas the \code{y} values were
#'   generated by adding draws from a random normal distribution
#'   (\eqn{s.d. = 0.1}) around a Sine curve.
"EgData129"
